config/routes.rb
Rails.application.routes.draw do
  root 'front#home'
  get 'front/about'
  get 'front/contact'
  get 'front/secret'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
	def home
		
	end

	def contact

	end

	def about
		@password = params[:password]
	end

	def secret
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/front/about.html.erb
<h1>About Page</h1>

<% if @password == "supersecret" %>
	<p>Almost there. Add duper!</p>
	<% elsif @password == "superdupersecret" %>
	<%= link_to 'Secret Page', front_secret_path %>
	<% else %>
<% end %>
		

app/views/front/contact.html.erb
<h1>Contact Page</h1>

app/views/front/home.html.erb
<h1>Home Page</h1>

app/views/front/secret.html.erb
<h1>Secret Page</h1>

app/views/layouts/_nav.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', front_about_path %>
<%= link_to 'Contact', front_contact_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Decypher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>